services:
  rabbit:
    image: rabbitmq:4.0-management
    container_name: michaelRabbit
    healthcheck:
      test: [ 'CMD', 'rabbitmqctl', 'status' ]
      interval: 60s
      timeout: 30s
      retries: 2
      start_period: 60s
      start_interval: 5s
    volumes:
      - data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbity

  right:
    build:
      context: .
      args:
        TARGET: right
    depends_on:
      rabbit:
        condition: service_healthy
    networks:
      - rabbity

  left:
    build:
      context: .
      args:
        TARGET: left
    depends_on:
      - right
    networks:
      - rabbity

networks:
  rabbity:
    driver: bridge
